Select the parent of the script containing `import.meta.document`
PolymerLabs/hd-html pull request #15
Opened 2019-05-07 14:59 UTC by aaronmars

See https://github.com/PolymerLabs/html-modules-toolkit/issues/14.
Aligns the transform for import.meta.document with the explainer/proposal at https://github.com/w3c/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md

2019-05-07 15:01 UTC, aaronmars commented
I signed it!

2019-05-07 18:53 UTC, cdata requested changes

2019-05-07 18:53 UTC, cdata commented on src/html-module-transform.ts
>        if (property.type === 'Identifier') {
I think the problem here is that this check is not specific enough. The condition is checking for usages of `import.meta.*` as an expression, but isn't particular about `import.meta.script` (the original use case) vs `import.meta.document`.

We should probably change the condition to something like:

```typescript
if (property.type === 'Identifier') {
  switch (property.name) {
    case 'script':
      // Do the current transform for script
      break;
    case 'document':
      // Do the new proposed transform for document
      break;
  }
}
```

2019-05-07 18:53 UTC, cdata commented
Thanks for looking into this 🙌 left a note, LMKWYT!

2019-05-09 17:54 UTC, aaronmars commented
Oh yeah. Wow. I completely mis-read the code there. Makes sense now!
I'll get that fixed up.

2026-05-01 17:29 UTC, closed without merging